
DEBUG_SPEW = 0
DEBUG = false
DEBUG_ABILITY_PAGES = false
DEBUG_CONSTRUCT_BUILDING = false
DEBUG_RESOURCES = false
DEBUG_SIMPLERTS = false
DEBUG_SIMPLE_BOT = false
DEBUG_SIMPLE_TECH_TREE = false
DEBUG_UTILS = false

START_GOLD = 500
START_LUMBER = 50
GOLD_PER_TICK = 0
--GOLD_PER_TICK = 1
GOLD_TICK_TIME = 1.0

BUYBACK_ENABLED = false
FIRST_BLOOD_ACTIVE = false
SAME_HERO_ENABLED = true
LOSE_GOLD_ON_DEATH = false

MINE_LIMIT = 1

KILLS_TO_WIN = 3

TREE_REGROW_TIME_SECONDS = 300

THINK_TIME = 0.1
HERO_SELECTION_TIME = 40.0
PRE_GAME_TIME = 35.00
POST_GAME_TIME = 30.00

-- Other
FIRST_PLAYER_INDEX_GOODGUYS = 0
FIRST_PLAYER_INDEX_BADGUYS = 5
HIGHEST_PLAYER_INDEX = 9

MAX_ABILITY_COUNT = 6
